# Generated by Django 3.0.7 on 2020-06-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.TextField(null=True, verbose_name='Описsание услуги'),
        ),
    ]
