# Generated by Django 3.0.7 on 2020-06-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0002_auto_20200629_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание услуги'),
        ),
    ]
