# Generated by Django 3.0.7 on 2020-06-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0003_auto_20200629_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='master',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_main.Master', verbose_name='Создатель цены'),
        ),
        migrations.AlterField(
            model_name='price',
            name='salon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_main.Salon', verbose_name='Салон'),
        ),
    ]
