# Generated by Django 3.0.7 on 2020-06-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0004_auto_20200629_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='post_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_medias', to='chat_main.Post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='price_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_medias', to='chat_main.Price', verbose_name='Услуга'),
        ),
    ]
