# Generated by Django 3.0.7 on 2020-06-29 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0005_auto_20200629_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_posts', to='chat_main.Master', verbose_name='Создатель поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_posts', to='chat_main.Salon', verbose_name='Пост Салона'),
        ),
        migrations.AlterField(
            model_name='price',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_prices', to='chat_main.Master', verbose_name='Создатель цены'),
        ),
        migrations.AlterField(
            model_name='price',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_prices', to='chat_main.Salon', verbose_name='Салон'),
        ),
    ]
