# Generated by Django 3.0.7 on 2020-07-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0006_auto_20200629_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
