# Generated by Django 3.0.7 on 2020-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0008_auto_20200705_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='average_time',
            field=models.IntegerField(default=0, verbose_name='Среднее время услуги'),
        ),
    ]
