# Generated by Django 3.0.7 on 2020-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0010_auto_20200705_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ManyToManyField(related_name='masters', to='chat_main.Master', verbose_name='Исполнители'),
        ),
    ]
