# Generated by Django 3.0.7 on 2020-07-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0011_auto_20200705_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='post_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_medias', to='chat_main.Post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='price_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_medias', to='chat_main.Price', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес салона'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='avatar',
            field=models.TextField(null=True, verbose_name='Фото салона'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название салона'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='Ссылка на страницу салона'),
        ),
    ]
