# Generated by Django 3.0.7 on 2020-07-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0012_auto_20200721_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='background',
            field=models.TextField(default=0, verbose_name='Задний фон'),
            preserve_default=False,
        ),
    ]
