# Generated by Django 3.0.7 on 2020-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0014_auto_20200721_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='background',
            field=models.TextField(null=True, verbose_name='Задний фон'),
        ),
    ]
