# Generated by Django 3.0.7 on 2020-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0016_remove_master_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='main_background',
            field=models.TextField(null=True, verbose_name='Задний фон'),
        ),
    ]
