# Generated by Django 3.0.7 on 2020-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0017_master_main_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='main_background',
        ),
        migrations.AddField(
            model_name='salon',
            name='main_background',
            field=models.TextField(null=True, verbose_name='Задний фон'),
        ),
    ]
