# Generated by Django 3.0.7 on 2020-08-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_main', '0020_auto_20200726_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='salon_masters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_masters', to='chat_main.Master', verbose_name='Мастера салона'),
        ),
    ]
